<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Aspire.Hosting" Version="13.5.3" />
    <PackageVersion Include="Aspire.Hosting.EntityFrameworkCore" Version="13.3.5-preview.1.26270.6" />
    <PackageVersion Include="Aspire.Hosting.Kafka" Version="13.5.3" />
    <PackageVersion Include="Aspire.Hosting.Docker" Version="13.5.3" />
    <PackageVersion Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
    <PackageVersion Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.3.5" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.5.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.5.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.2" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.15.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.1" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.2.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.0" />
    <PackageVersion Include="grate-devs.grate" Version="2.0.5" />
  </ItemGroup>
</Project>