<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageTags>aspire hosting kafka topic</PackageTags>
    <Description>Kafka topic creation hosting support for Aspire.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" />
    <PackageReference Include="Aspire.Hosting.Kafka" />
  </ItemGroup>
</Project>
