<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageTags>aspire hosting grate migrations database sql postgresql</PackageTags>
    <Description>grate SQL migration runner hosting support for Aspire.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>
</Project>
